/* tslint:disable */
// This file is generated
// Do not edit this file
import * as createTable from "./createTable/index";
export * as createTable from "./createTable/index";
import * as dropTable from "./dropTable/index";
export * as dropTable from "./dropTable/index";
import * as insertData from "./insertData/index";
export * as insertData from "./insertData/index";
import * as deleteData from "./deleteData/index";
export * as deleteData from "./deleteData/index";
import * as updateData from "./updateData/index";
export * as updateData from "./updateData/index";
import * as queryData from "./queryData/index";
export * as queryData from "./queryData/index";
import * as customQuery from "./customQuery/index";
export * as customQuery from "./customQuery/index";

export type Actions = {
  createTable: createTable.ActionCreateTable;
  dropTable: dropTable.ActionDropTable;
  insertData: insertData.ActionInsertData;
  deleteData: deleteData.ActionDeleteData;
  updateData: updateData.ActionUpdateData;
  queryData: queryData.ActionQueryData;
  customQuery: customQuery.ActionCustomQuery;
}
